name: Paprika
version: 0.1
description: A bridge plugin that lets you write Minecraft plugins in lua
main: net.ioixd.paprika.Paprika
commands:
  lua:
    description: Execute a Lua function
    usage: /<command>