from os.path import exists
import gen_json, json

# If there's no unsafe_lib.json, create it. Otherwise, load it.
unsafe_lib_body = ""
if(exists("./unsafe_lib.json")):
    print("unsafe_lib.json found, opening")
    f = open("./unsafe_lib.json", "r")
    unsafe_lib_body = f.read()
    f.close()
else:
    print("unsafe_lib.json not found, creating")
    doc = gen_json.parse_javadoc("https://hub.spigotmc.org/javadocs/spigot/org/bukkit/package-tree.html")
    unsafe_lib_body = doc.toJSON().replace("\n","",99999999)
    f = open("unsafe_lib.json", "w")
    f.write(unsafe_lib_body)
    f.close()

unsafe_lib = json.loads(unsafe_lib_body)

f = open("UnsafeLibrary.java", "w")
f.truncate()

f.write("""
/*
    This file is generated by a Python script. Do not make direct modifications to it.
    Please modify the script that generates it instead.
*/
""")

for c in unsafe_lib["classes"]:
    f.write("import "+c["name"]+"\n")

f.write("""
public class UnsafeLibrary {
""")



f.write("""
}
""")

f.close()